config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :tareas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "tareas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  belongs_to :usuario
  validates :titulo, presence: true
  validates :descripcion, presence: true, length: { minimum: 5 }
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :tareas, dependent: :destroy
    #validates :nombre, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :set_tarea, only: %i[ show edit update destroy ]
  before_action :authenticate_usuario!
  # GET /tareas or /tareas.json
  def index
    @tareas = Tarea.all
  end

  # GET /tareas/1 or /tareas/1.json
  def show
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
  end

  # GET /tareas/1/edit
  def edit
  end

  # POST /tareas or /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to tarea_url(@tarea), notice: "Tarea was successfully created." }
        format.json { render :show, status: :created, location: @tarea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tareas/1 or /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html { redirect_to tarea_url(@tarea), notice: "Tarea was successfully updated." }
        format.json { render :show, status: :ok, location: @tarea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1 or /tareas/1.json
  def destroy
    @tarea.destroy!

    respond_to do |format|
      format.html { redirect_to tareas_url, notice: "Tarea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarea
      @tarea = Tarea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarea_params
      params.require(:tarea).permit(:titulo, :descripcion, :completado, :usuario_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App Tareas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tareas/_form.html.erb
<%= form_with(model: tarea) do |form| %>
  <% if tarea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tarea.errors.count, "error") %> prohibited this tarea from being saved:</h2>

      <ul>
        <% tarea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :completado, style: "display: block" %>
    <%= form.check_box :completado %>
  </div>

  <div>
    <%= form.label :usuario_id, "Usuario" %>
    <%= form.collection_select :usuario_id, Usuario.all, :id, :nombre, prompt: "Selecciona un usuario" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tareas/_tarea.html.erb
<div id="<%= dom_id tarea %>">
  <p>
    <strong>Titulo:</strong>
    <%= tarea.titulo %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= tarea.descripcion %>
  </p>

  <p>
    <strong>Completado:</strong>
    <%= tarea.completado %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= tarea.usuario_id %>
  </p>

</div>

app/views/tareas/edit.html.erb
<% content_for :title, "Editing tarea" %>

<h1>Editing tarea</h1>

<%= render "form", tarea: @tarea %>

<br>

<div>
  <%= link_to "Show this tarea", @tarea %> |
  <%= link_to "Back to tareas", tareas_path %>
</div>

app/views/tareas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tareas" %>

<h1>Tareas</h1>

<div id="tareas">
  <% @tareas.each do |tarea| %>
    <p>
      <strong>Título:</strong>
      <%= tarea.titulo %>
    </p>

    <p>
      <strong>Descripción:</strong>
      <%= tarea.descripcion %>
    </p>

    <p>
      <strong>Completado:</strong>
      <%= tarea.completado ? 'Sí' : 'No' %>
    </p>

    <p>
      <strong>Usuario:</strong>
      <%= tarea.usuario.nombre %>
    </p>

    <p>
      <%= link_to "Show this tarea", tarea %>
    </p>
  <% end %>
</div>

<%= link_to "New tarea", new_tarea_path %>

app/views/tareas/new.html.erb
<% content_for :title, "New tarea" %>

<h1>New tarea</h1>

<%= render "form", tarea: @tarea %>

<br>

<div>
  <%= link_to "Back to tareas", tareas_path %>
</div>

app/views/tareas/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @tarea.titulo %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @tarea.descripcion %>
</p>

<p>
  <strong>Completado:</strong>
  <%= @tarea.completado ? 'Sí' : 'No' %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @tarea.usuario.nombre %>
</p>

<div>
  <%= link_to "Edit this tarea", edit_tarea_path(@tarea) %> |
  <%= link_to "Back to tareas", tareas_path %>

  <%= button_to "Destroy this tarea", @tarea, method: :delete %>
</div>